### ISSUE TITLE
Fails to build with GHC 9.2

### ISSUE THREAD

**Issue by robx** [nikita-volkov/ptr#2]
Building with GHC 9.2.2 on macOS, I see:

```
library/Ptr/UncheckedShifting.hs:65:36: error:
    • Couldn't match expected type ‘Word16#’ with actual type ‘Word#’
    • In the first argument of ‘W16#’, namely
        ‘(w `uncheckedShiftRL#` i)’
      In the expression: W16# (w `uncheckedShiftRL#` i)
      In an equation for ‘shiftr_w16’:
          shiftr_w16 (W16# w) (I# i) = W16# (w `uncheckedShiftRL#` i)
   |
65 | shiftr_w16 (W16# w) (I# i) = W16# (w `uncheckedShiftRL#`   i)
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^

library/Ptr/UncheckedShifting.hs:66:36: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely
        ‘(w `uncheckedShiftRL#` i)’
      In the expression: W32# (w `uncheckedShiftRL#` i)
      In an equation for ‘shiftr_w32’:
          shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#` i)
   |
66 | shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#`   i)
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is probably what PR #1 addresses? Would be neat to get a release with that fix if it's good.

**Comment by robx** [comment]
(Also not sure how you feel about hackage revisions, but it'd be great to have a tighter upper bound on base for the existing release(s), so we get planning failures instead of build failures.)

**Comment by nikita-volkov** [comment]
Fix is released as 0.16.8.2.

> it'd be great to have a tighter upper bound on base for the existing release(s), so we get planning failures instead of build failures

Unfortunately it's more maintenance burden. I'll skip it for now.
